
  SELECT [Description]
  FROM PRODUCTS
  JOIN BRANDS ON BRANDS.BrandName = PRODUCTS.BrandName
  WHERE(Price < 5.00) AND (BRANDS.BrandName = 'Local');

  SELECT PRODUCTS.UPC, DISTRIBUTORS.Name, DIST_PRODUCTS.WHCost
  FROM PRODUCTS 
  JOIN DIST_PRODUCTS
  ON PRODUCTS.UPC = DIST_PRODUCTS.UPC
  JOIN DISTRIBUTORS
  ON DIST_PRODUCTS.DistID = DISTRIBUTORS.DistID
  WHERE PRODUCTS.UPC = 36289367281;

  --pulling OR instead of AND
  SELECT CERT_PRODUCTS.UPC, PRODUCTS.Description, CERT_PRODUCTS.CertName
  FROM PRODUCTS
  JOIN CERT_PRODUCTS ON PRODUCTS.UPC = CERT_PRODUCTS.UPC
  JOIN LOCATION_PRODUCTS ON PRODUCTS.UPC = LOCATION_PRODUCTS.UPC
  WHERE CERT_PRODUCTS.CertName = 'Halal' OR CERT_PRODUCTS.CertName = 'Kosher' AND (LOCATION_PRODUCTS.InBack > 0 OR LOCATION_PRODUCTS.OutFront > 0);

SELECT	PRODUCTS.Description
FROM	PRODUCTS
JOIN	TAGGED_PRODUCTS ON PRODUCTS.UPC = TAGGED_PRODUCTS.UPC
JOIN	TAGS ON TAGGED_PRODUCTS.TagName = TAGS.TagName
WHERE	TAGS.TagName = 'Made by hand';

SELECT	MAKERS.MakerName, SUM(COUPONS.AmountSaved) as 'Owes'
FROM	COUPONS
JOIN	ORDERED_PRODUCTS ON COUPONS.CouponID = ORDERED_PRODUCTS.CouponID
JOIN	PRODUCTS ON ORDERED_PRODUCTS.UPC = PRODUCTS.UPC
JOIN	BRANDS ON PRODUCTS.BrandName = BRANDS.BrandName
JOIN	MAKERS ON BRANDS.MakerName = MAKERS.MakerName
WHERE	ORDERED_PRODUCTS.CouponPaid = 'n'
GROUP BY MAKERS.MakerName;

SELECT	CUSTOMERS.Fname, CUSTOMERS.Lname, ORDERS.PaymentType
FROM	CUSTOMERS
JOIN	ORDERS
ON		CUSTOMERS.MemberID = ORDERS.MemberID
WHERE	CUSTOMERS.Fname = 'Megan' AND CUSTOMERS.Lname = 'Brown';
