		--fix this
		SELECT	PRODUCTS.UPC
		FROM	PRODUCTS
		JOIN	LOCATION_PRODUCTS ON PRODUCTS.UPC = LOCATION_PRODUCTS.UPC
		WHERE	InBack > 0 AND OutFront = 0;

		SELECT	PRODUCTS.UPC, PRODUCTS.Description, (COUNT(LOCATION_PRODUCTS.LocationName)) as 'Locations'
		FROM	PRODUCTS
		JOIN	LOCATION_PRODUCTS ON PRODUCTS.UPC = LOCATION_PRODUCTS.UPC
		GROUP BY PRODUCTS.UPC, PRODUCTS.Description
		ORDER BY Locations DESC;

		--fix this
		SELECT	PRODUCTS.Description, ORDERS.OrderTime
		FROM	PRODUCTS
		JOIN	ORDERED_PRODUCTS ON PRODUCTS.UPC = ORDERED_PRODUCTS.UPC
		JOIN	ORDERS ON ORDERED_PRODUCTS.OrderID = ORDERS.OrderID
		WHERE	ORDERS.MemberID = 2;
 
		SELECT 	PRODUCTS.Description, PRODUCTS.UPC, PRODUCTS.MinOrderCount, (LOCATION_PRODUCTS.OutFront + LOCATION_PRODUCTS.InBack) AS 'InStock'
		FROM 	PRODUCTS
		JOIN	LOCATION_PRODUCTS ON PRODUCTS.UPC = LOCATION_PRODUCTS.UPC
		WHERE	PRODUCTS.MinOrderCount > (LOCATION_PRODUCTS.OutFront + LOCATION_PRODUCTS.InBack);
 
		SELECT	ORDERS.MemberID, PRODUCTS.Description
		FROM	PRODUCTS
		JOIN	BRAND_MAKERS ON PRODUCTS.MakerName = BRAND_MAKERS.MakerName
		JOIN	BRANDS ON BRAND_MAKERS.BrandName = BRANDS.BrandName
		JOIN	ORDERED_PRODUCTS ON PRODUCTS.UPC = ORDERED_PRODUCTS.UPC
		JOIN	ORDERS ON ORDERED_PRODUCTS.OrderID = ORDERS.OrderID
		WHERE	BRANDS.BrandName = 'Local';

		SELECT	CUSTOMERS.MemberID, (SUM(ORDERED_PRODUCTS.Quantity)) as 'ProductsPurchased'
		FROM	ORDERED_PRODUCTS
		JOIN	ORDERS ON ORDERS.OrderID = ORDERED_PRODUCTS.OrderID
		JOIN	CUSTOMERs ON ORDERS.MemberID = CUSTOMERS.MemberID
		WHERE CUSTOMERS.MemberID = 1
		GROUP BY CUSTOMERS.MemberID;
		
		--fix this
 		SELECT	DISTINCT CUSTOMERS.MemberID, (ORDERED_PRODUCTS.Quantity * PRODUCTS.Price) as 'TotalSpent'
		FROM 	CUSTOMERS
		JOIN	ORDERS ON CUSTOMERS.MemberID = ORDERS.MemberID
		JOIN	ORDERED_PRODUCTS ON ORDERED_PRODUCTS.OrderID = ORDERS.OrderID
		JOIN	PRODUCTS ON PRODUCTS.UPC = ORDERED_PRODUCTS.UPC
		GROUP BY CUSTOMERS.MemberID, ORDERED_PRODUCTS.Quantity, PRODUCTS.Price
