SELECT	CUSTOMERS.Email, (SUM(ORDERED_PRODUCTS.Quantity)) as 'ProductsPurchased'
FROM	ORDERED_PRODUCTS
JOIN	ORDERS
ON		ORDERS.OrderID = ORDERED_PRODUCTS.OrderID
JOIN	CUSTOMERS
ON		ORDERS.MemberID = CUSTOMERS.MemberID
GROUP BY CUSTOMERS.Email
ORDER BY ProductsPurchased DESC
		
SELECT		DISTRIBUTORS.Name, PRODUCTS.Description, DIST_PRODUCTS.WHCost
FROM		PRODUCTS
JOIN		DIST_PRODUCTS
ON			PRODUCTS.UPC = DIST_PRODUCTS.UPC
JOIN		DISTRIBUTORS
ON			DIST_PRODUCTS.DistID = DISTRIBUTORS.DistID
WHERE		WHCost < 5
ORDER BY	DISTRIBUTORS.Name

SELECT 		PRODUCTS.Description, PRODUCTS.Price, PRODUCTS.MakerName, MAKERS.Address
FROM		PRODUCTS
JOIN		MAKERS
ON			PRODUCTS.MakerName = MAKERS.MakerName
WHERE 		PRODUCTS.Price > 5;

